### ISSUE TITLE
something wrong is not right ...

### ISSUE THREAD

**Issue by GM-Ricker** [crashinvaders/gdx-texture-packer-gui#101]
As in the image below ... every time I edit or create a sprite and do the packaging process ... when I try it out I try the command to expand the image only that instead of it expanding it stretches as if zooming. .. or this is a texture packer bug, or I am not sure how to configure mine ... please I need an answer because I can't solve this problem, and when I test with the standard libGDX spriteshhet it expands and doesn't it stretches, but when it comes to my own arts it happens. please someone help me!

image of how it should be (with libgdx default asset)
![Sem título2](https://user-images.githubusercontent.com/57239750/112227174-fd799800-8c0d-11eb-93d0-0d9246b2e8d5.png)

image of when I use my own package(I used 2 different pixel art editors)
![Sem título](https://user-images.githubusercontent.com/57239750/112070694-f63e8580-8b4c-11eb-973e-3bb6ae88703f.png)

code image
![Sem título3](https://user-images.githubusercontent.com/57239750/112227305-37e33500-8c0e-11eb-9ea0-bcec88630a56.png)

**Comment by metaphore** [comment]
Hi there,
I'm not entirely sure what's the problem you have.
Could you please show the actual texture atlas image file?
How do you add the image to the stage?

On a side note, if you have any troubles configuring LibGDX/Scene2D or anything else related to the actual code, you better of seeking for help at [LibGDX Discord server](https://discord.gg/uK73s98e).

**Comment by GM-Ricker** [comment]
I edited the post so you can better understand the problem

**Comment by metaphore** [comment]
It's still hard to tell what's going on unless you actually demonstrate the differences of the atlases you use.
It would help a lot if you would attach both `.atlas` data files and `.png` page images for each of the atlases (one from the original LibGDX texture packer output and another one from GDX Texture Packer tool).

**Comment by GM-Ricker** [comment]
[assets.zip](https://github.com/crashinvaders/gdx-texture-packer-gui/files/6201209/assets.zip)

**Comment by metaphore** [comment]
Just from looking at the differences between those two atlases, I can see that the 9patch regions from `uiskin.atlas` are packed as plain images (non-9patch) for `graphics.atlas`.

If you don't know what 9patch is, I'd recommend starting from [reading about it](https://github.com/libgdx/libgdx/wiki/Texture-packer#ninepatches) and checking on how to pack them with the original LibGDX texture packer.

Speaking of GDX Texture Packer GUI project's 9patch capabilities, you can turn any _regular_ image into a 9patch using a built-in tool. 
![gdxtp-ninepatch-demo0](https://user-images.githubusercontent.com/6159734/112681178-e900fe00-8ea0-11eb-9f8e-c077ebb8854b.gif)

If you have any other general questions outside of this project specifics, please consider using the official [LibGDX Discord server](https://discord.gg/uK73s98e) or [LibGDX tag on StackOverflow](https://stackoverflow.com/questions/tagged/libgdx), there are plenty of people willing to help. The GitHub issues section is for bugs and feature requests only.

**Comment by GM-Ricker** [comment]
do you mean i have to convert my PNG with this 9patch to not happen what i show in the images? um I thought it was just selecting the PNGs as I saw on some YouTube tournaments
