### ISSUE TITLE
Relative Path input

### ISSUE THREAD

**Issue by ange-black69** [crashinvaders/gdx-texture-packer-gui#102]
Is it possible to have input file as a relative path of the .tpproj ? 
For example, I would like to share to my friend the .tpproj file with the images to be packed along the .tpprojet file.

**Comment by metaphore** [comment]
All the file paths are kept as relative to the project file already. Do you have any issues?

**Comment by ange-black69** [comment]
thanks for the answer.
The problem I am facing is the input and output dir.
When I click on the "add input file" I must select images path in absolute path, I dont have a way to select relatively based on where the .tpprojet is you know what I mean? 
Same things for the ouput..

**Comment by metaphore** [comment]
I'm not sure if I'm reading you right. When you choose an image, its path gets converted to be relative to the `.tpproj` file location. So once you save the project, it's safe to copy/move (or add to a git repo) all the images along with the `.tpproj` file and it will open just fine.

So once again, can explain the actual issue you're experiencing (if any)?

**Comment by ange-black69** [comment]
Ho nice, don't know this feature was basically implemented because I didn't see anywhere such feature.
So the issue is closed :)
