### ISSUE TITLE
Setting to keep extensions

### ISSUE THREAD

**Issue by GniLudio** [crashinvaders/gdx-texture-packer-gui#108]
# Keep Extension Setting

## Suggestion
It would be nice if it would be possible to keep the file extensions,
so that it would be possible to have the same paths in code.

## Why?
Changing from Texture to TextureRegion (or vice versa) in code wouldn't change the path...

**Comment by metaphore** [comment]
Not sure what kind of files are you talking about? Atlas data files or page image files?

**Comment by GniLudio** [comment]
I want to keep the extensions of the old image file extensions in the region names.
So that the image `ui/screen/loadingScreen/background.png` has the same region name in the texture atlas.
(Now it would be `ui/screen/loadingScreen/background`)

**Comment by metaphore** [comment]
Ah I see. I don't think that would be that difficult to do. Will keep it on the list for the next release.

**Comment by GniLudio** [comment]
@metaphore Beautiful. Should I close the issue then?

**Comment by metaphore** [comment]
Please keep it open. I'll make sure it's closed when the feature is implemented.

**Comment by metaphore** [comment]
The setting is available now at the end of "Pack settings" section and configures this behavior on per atlas basis.

![image](https://user-images.githubusercontent.com/6159734/134465754-88821e7e-21b6-46a0-b00e-6594102b32c3.png)
