### ISSUE TITLE
New atlas format

### ISSUE THREAD

**Issue by RUSshy** [crashinvaders/gdx-texture-packer-gui#11]
Hello

Would be cool to add new format for the texture atlas like JSON or XML or even binary format for faster loading and it's easier to parse for other things than libGDX game dev :)

Thanks for this tool, i love it!

**Comment by metaphore** [comment]
It may sound weird, but packing itself is out of project scope, especially writing of data file. Packing proceedure is fully based on original [LibGDX TexturePacker](https://github.com/libgdx/libgdx/wiki/Texture-packer) code and cannot be easily modified now. Though it's a good idea to expand project capabilities, but I'm sorry to say that for now this cannot be a priority.
