### ISSUE TITLE
Freeze on Pack [Ubuntu 21.04]

### ISSUE THREAD

**Issue by theovier** [crashinvaders/gdx-texture-packer-gui#111]
Hi,

the TexturePacker seems to freeze on my system (Ubuntu 21.04) during the pack process. I tried to pack 3 images (64x64 pixels) 
into one atlas. After clicking _pack_ I'm presented with the usual dialog, however it never ends. I had it open for roughly 20 minutes before closing it. The dialogue is still responsive tho and I can cancel the dialog at anytime and trigger the packing again. 
Unfortunately, it also freezes then. I also tried to play around with the properties, without any success. I've attached the generated log file.

![gdx_texture_packer_unresponsive](https://user-images.githubusercontent.com/13664498/129352407-6bd6ec13-7be4-424d-bf66-93153a0574a9.png)

Version: 4.10.0
OS: Linux 5.11.0-25-generic amd64
JRE: 11.0.11 Ubuntu
GPU: NV164
OpenGL vendor: nouveau
OpenGL version: 4.3 (Compatibility Profile) Mesa 21.0.3
[ExtensionModuleRepositoryService] Cached data was loaded
[ConfigurationController] Incremental fonts are disabled
[VisUI] Warning, using invalid libGDX version for VisUI 1.4.8.
You are using libGDX 1.9.11 but you need 1.9.12. This may cause unexpected prob>
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt

**Comment by metaphore** [comment]
Hi there, thanks for the report.

It might be something is crashing during the packaging process in the background, but the program doesn't catch it for some reason.

Could you please start the app in the terminal (locate the installation dir and call the launcher `.sh` file). That way you can see the full log in the runtime. Once you start packing an atlas, I'm pretty sure something is gonna come up in there.

**Comment by theovier** [comment]
Hi, 

thanks for the fast response. 

(Un-)fortunately I was not able to reproduce the problem again. I started up the `.sh` file and was ready to see some error but it worked perfectly :smile: 

I have no clue which hickup may caused this, however, it seems to work fine now. Again, thanks for the answer and I think you can close this issue. 

Sorry for the inconvenience.

**Comment by metaphore** [comment]
No worries.
Please feel free to reopen this issue and post any details if the problem comes back again.
