### ISSUE TITLE
Unable to select some atlases with 4.10.1

### ISSUE THREAD

**Issue by WickedShell** [crashinvaders/gdx-texture-packer-gui#122]
Opening my old project file that builds fine with 4.9 encounters several issues with 4.10.1.
 - If I open the project and attempt to click on the atlas called `nearest` it instead just builds the `linear` atlas again. I can't find anyway to click in and actually edit any of the settings for `nearest` despite seeing it in the list.
 - If I pack all the textures it does actually spend time processing the `nearest` atlas, and writes it out to disk, however the format that is written out doesn't load within my project. I see in the 4.10.0 release notes that it now uses the newer format that was released in LibGDX 1.9.13, but since I'm using LibGDX 1.9.14 so I would have expected the support for the new format. Is there an actual API change I need to make to support loading this newer format?

The 4.9.0 release of the texture packer works fine. I've attached the project file in the zip. Please let me know if there is any more information you need, or steps from me.
[project.zip](https://github.com/crashinvaders/gdx-texture-packer-gui/files/7686928/project.zip)

**Comment by metaphore** [comment]
Thanks so much for submission!
Apparently there's a critical regression bug in the code and it is now impossible to select atlases from the pack list.
To be clear, it has nothing to do with the data format and your old project file should be working fine with the latest releases. It has no issues with [4.10.0](https://github.com/crashinvaders/gdx-texture-packer-gui/releases) for example, you may consider switching back to it until the new version is out (a few weeks).

Regarding the LibGDX new atlas format, I'm not sure if they the old one is still supported in 1.10.0, but you surely can export in both without problems. Just uncheck this option on the "Pack Settings" panel.

![image](https://user-images.githubusercontent.com/6159734/146094059-957401da-8083-4039-ad9e-2d2f59a67dd2.png)
