### ISSUE TITLE
Packing two images with the same name but different paths will omit one of them

### ISSUE THREAD

**Issue by Rubonnek** [crashinvaders/gdx-texture-packer-gui#131]
Just as the title says, packing two images with the same name but different paths will omit one of them.

For example, adding the following two PNGs individually to the pack files list:
```
same_name_but_different_textures
├── same_name.png
└── subdir
    └── same_name.png
```

and then packing them, will omit one of the images in the emitted atlas. I expected a warning or an error but that was not the case.

Archive used in the example above: [same_name_but_different_textures.zip](https://github.com/crashinvaders/gdx-texture-packer-gui/files/8886509/same_name_but_different_textures.zip)

**Comment by agvoron** [comment]
I don't maintain this repo, just happened to be playing with it today. See the flattenPaths option. "If true, subdirectory prefixes are stripped from image file names. Image file names should be unique." Maybe that's what you're looking for.

**Comment by Rubonnek** [comment]
Thanks for mentioning it. I did test the flatten paths option before opening the issue and the same happens with it enabled. Disabling the path flattening will make both images show up in the atlas.

I don't mind the behavior, but omitting these images shouldn't happen silently.

**Comment by metaphore** [comment]
Hi @Rubonnek 
Thanks for the report.

In fact the warning is present, but it is only visible in the output console
![image](https://user-images.githubusercontent.com/6159734/173287116-59d42e4d-2b79-4491-a4a1-57ed4d4c9f43.png)

The app's behavior is to halt the packing process and display the output only on errors. Warnings are more or less go silent. I think it's a good idea to somehow at least notify the user about them.

WIll add this to the next release.
