### ISSUE TITLE
Non-Visible Drive Letters

### ISSUE THREAD

**Issue by austeregrim** [crashinvaders/gdx-texture-packer-gui#135]
Drive letters are not visible: This is my first run of the software, I'm sure it's just a dark mode issue or something but this is my first experience with the software.

![image](https://user-images.githubusercontent.com/1243145/179020462-e80de58e-28df-40c9-af30-ff748450b25c.png)

**Comment by metaphore** [comment]
In the latest [4.11.0 release](https://github.com/crashinvaders/gdx-texture-packer-gui/releases/tag/4.11.0), the app switched to a native file picker dialog. Which means this bug is rendered outdated.
