### ISSUE TITLE
[Suggestion] Support JSON format of output config file.

### ISSUE THREAD

**Issue by finscn** [crashinvaders/gdx-texture-packer-gui#15]
The content of *.atlas is very simple and clear.
But for html5/web game ,  the developers have to parse it by themselves via javascript.

If gdx-texture-packer-gui could support JSON , I think it will get broader range of applications.

**Comment by metaphore** [comment]
As was mentioned in #11 for now it's out of priority. This project intentionally targets only LibGDX atlas format and support for others is a very complicate thing. So probably few iterations later we will get back to this feature.

**Comment by RUSshy** [comment]
Maybe just convert the current .atlas format

I mean once the texture packer finish his job, you take the .atlas and convert it, i might try to do that and send a PR

**Comment by metaphore** [comment]
@RUSshy this might work, but as I see it, it's much cleaner to customize data format in a first place. If you ever have a chance to try https://www.codeandweb.com/texturepacker they have kinda scripting engine that allows to customize output format completely and I think this is something that we should have as well. But at first I need to extract TexturePacker's code that is used to generate data file so we can customize it properly.

For now, I would recommend you write your own tool for conversion and if this will work, I could look into proper integration for the next version.
