### ISSUE TITLE
When I set scale to 2.0 , there are many error logs.

### ISSUE THREAD

**Issue by finscn** [crashinvaders/gdx-texture-packer-gui#16]
see the image : 
<img width="849" alt="2017-04-10 5 04 06" src="https://cloud.githubusercontent.com/assets/288367/24853915/2b5e2a40-1e0f-11e7-83e9-5217af7bfac3.png">

**Comment by finscn** [comment]
Sorry . I'm a newbie of gdx-texture-packer-gui  , and my english is very bad . 
So ... this is my fault again...

**Comment by RUSshy** [comment]
It says it is too big image, you need to increase max size

Google Translate:
它说它太大了，你需要增加最大尺寸
