### ISSUE TITLE
[Feature Request] Built-in 9-patch editor

### ISSUE THREAD

**Issue by RUSshy** [crashinvaders/gdx-texture-packer-gui#18]
Hello

Would be cool to be able to edit 9-patch regions from the GUI instead of manually doing it inside the .atlas file

Would make ui skin making so easier

Thanks

**Comment by metaphore** [comment]
Yeah, it's a good idea. Not sure if I can add it to the next version, but certainly will do it someday. Let's keep it open until then.

**Comment by metaphore** [comment]
Done, now we have a built in simple nine patch editor as well as an ability to create 9-patches on the fly during packing right from the plain PNGs.

![image](https://cloud.githubusercontent.com/assets/6159734/26750089/4054cba2-4844-11e7-9a59-8bd356ffac22.png)
