### ISSUE TITLE
Pack input files aren't ordered properly

### ISSUE THREAD

**Issue by otoomey** [crashinvaders/gdx-texture-packer-gui#19]
I have 24 images, all labeled from 0001.png to 0024.png. When I select all of them and open them up, they get ordered correctly in the [Pack Files panel](https://gyazo.com/4183f237f0c2894b532656bd593b719c). However, when I pack them, the order of the pages is seemingly completely random.

I am not sure if this behaviour is intended. I would have assumed that you were using Alphanumeric sorting for the pictures.

**Comment by metaphore** [comment]
Image names are completely ignored by packer, it operates only with image sizes to pack them as efficient as possible (max rectangles packing). Since regions are retained only by name, there is no reason to keep image order inside packed atlas. So yes, this is intended behavior.

Why do you need to keep specific region order, by the way?

**Comment by otoomey** [comment]
I want to keep the order because the images are part of an animation.

**Comment by metaphore** [comment]
The problem is images randomly fall into different pages, right?

**Comment by otoomey** [comment]
yes

**Comment by otoomey** [comment]
It turns out that the atlas orders the pages correctly, despite the preview window not doing so.

**Comment by metaphore** [comment]
This is mostly up to packaging algorithm now and from what I see (~750 lines of code) it wont be easy to modify this behavior to control region order in that way.

Anyway, I'm not sure there will be significant benefits even if images were packed in order precisely. The fact is you do have multiple pages already and just can't bypass texture rebind while rendering. So, I'm sorry, but I could only recommend to play with atlas settings (like page size) or organize animation in some other way to reduce page amount at all cost.

**Comment by otoomey** [comment]
The issue that I have is that the preview window does not show the pages in the same order as the image input panel. You could 'fix' this very simply by sorting them in your [AtlasModel class](https://github.com/crashinvaders/gdx-texture-packer-gui/blob/master/core/src/com/crashinvaders/texturepackergui/views/canvas/AtlasModel.java) using a function like this:

```
private static Array<TextureAtlas.AtlasRegion> sortRegionsAlphabetically(Array<TextureAtlas.AtlasRegion> regions) {
    HashMap<String, TextureAtlas.AtlasRegion> values = new HashMap<>();

    for(TextureAtlas.AtlasRegion region: regions){
        values.put(region.name, region);
    }

    SortedSet<String> keys = new TreeSet<>(values.keySet());

    Array<TextureAtlas.AtlasRegion> sorted = new Array<>();

    for (String key : keys) {
        sorted.add(values.get(key));
    }
    return sorted;
}
```

**Comment by metaphore** [comment]
Nope. Preview panel is just displaying actual packed page texture and has nothing related to data order. Either I get you wrong, or you missed something.
