### ISSUE TITLE
Option to rewrite existing pack result

### ISSUE THREAD

**Issue by prineside** [crashinvaders/gdx-texture-packer-gui#21]
Using version 4.4.0

When we pack textures into existing package, TexturePacker checks old package for region names that already exist and throws an exception:
```
com.badlogic.gdx.utils.GdxRuntimeException: A region with the name "somename" has already been packed: somename
at com.badlogic.gdx.tools.texturepacker.TexturePacker.writePackFile(TexturePacker.java:294)
```

I use one folder where I store all of my textures to be packed and I don't remove them, that's why I get this exception each time I pack textures again and it forces me to manually remove old pack files. It also breaks old package when new textures added / old textures removed / textures size changed, because atlas image is generated and overwrites old one before exception is thrown. 

It would be nice to have a checkbox like "Append to pack" / "Overwrite existing regions" / "Overwrite pack file if exists" (like in old texture packer gui, where regions were not appended).

**Comment by metaphore** [comment]
Thanks for the report. App actually always replaces old pack file, but due to the latest changes in the `4.4` version old file deletion functionally was broken in a certain way for a case where pack doesn't use default `.atlas` extension and I believe that's what caused the problem.
