### ISSUE TITLE
4.4.0 'Use indices' broken

### ISSUE THREAD

**Issue by DarkJymis777** [crashinvaders/gdx-texture-packer-gui#23]
Hi,
I've tried Gdx TexturePacker GUI 4.4.0 on Windows Seven and Mac OS Sierra. On both, 'Use indices' setting doesn't work.
I've tried 4.3.2, same settings, and it works.

Maybe a conflict linked to change from 'input directory' to drag and drop function ?

**Comment by metaphore** [comment]
Hm, just checked it and it does work on Win and Linux, and I'm pretty sure there is no issue on Mac as well. Also I found no any difference in behavior between input directory and separated images. Are you sure you use proper file suffix for indexed images (like `image_N.png`)?

![gdx-tp-index-test0](https://user-images.githubusercontent.com/6159734/27253523-6c8c85d6-53a0-11e7-9ec4-9d13beecb715.gif)

Are you sure

**Comment by DarkJymis777** [comment]
Yep i did. I've reinstalled 4.4.0, and loaded the project i've saved with 4.3.2: the problem remains even with same settings…

I thought to use an older version after some researches and found that 
'Which TexturePacker are you using, by the way? The reason I ask is I'm now remembering that people occasionally ask questions on here and their problems have to do with them using TexturePacker-gui, which is based on a very outdated TexturePacker.' (Jun 3 '16)

Btw, no matter the version, 'use indices' function seem useless if 'grid layout' is unchecked, because sprites on the result atlas aren't ordered.  
Is it normal, or is it a curiosity on my side again ?

**Comment by metaphore** [comment]
Probably the issues comes from a specific settings set. Can you please drop here your `.tpproj` file, so I will try to reproduce it with your project configuration.

Sprites are always in a random order. That was never the point to arrange them anyhow other than optimal by size for packing. But for the grid this really looks a bit odd, because I truly have no idea who could use this checkbox on purpose now. But what for the indices, it actually does useful despite of packed order, because common case is use indexed sequence of regions to instantiate animation. In LibGDX, texture atlas is not supposed to be used with a direct region access, but only search by their names.

**Comment by DarkJymis777** [comment]
[ned_spritesheet.zip](https://github.com/crashinvaders/gdx-texture-packer-gui/files/1083004/ned_spritesheet.zip)

We work with Godot Engine. A programmer want us to use crammed sheets for less memory load.  
As we currently use png, it's ok for tilesets, but for spritesheets i think it's better for everyone to have ordered sprites.

**Comment by metaphore** [comment]
Sounds reasonable. Well, I can add simple sorting to grid based packer, so it will order regions by name and index.

Back to the indices problem. I played a little with your configuration, but unfortunately had no no luck in reproducing the bug yet. Can you please show me your invalid `.atlas` file that has no indices?

**Comment by DarkJymis777** [comment]
[ned_koala_atlas.zip](https://github.com/crashinvaders/gdx-texture-packer-gui/files/1083344/ned_koala_atlas.zip)
In fact, I notice i've misunderstood 'use indices' function, due to result that i want (ordered spritesheet) and failure to get that result with 4.4.0, which is the real issue for me. My bad.

Indeed, with 'use indices' setting, it shows 'imageName idx:Xnumber' for each sprite in the atlas preview. So, that function seem to do its job.
But as i dont use atlas files (i don't know if a nice importer exist for Godot…) but png, idx are useless for me.

What is strange is:
grid layout + use indices settings
4.3.2: sprites ordered
4.4.0: sprites no more ordered
That's why i've focused on that 'use indices' setting…
So 'simple sorting to grid based packer, so it will order regions by name and index' seems to workin previous version, but is no more present with 4.4.0. Or maybe it was a voluntary removal ?

What should be really nice: cramming with 'strip whitespaces' settings and keep sprites ordered as most as possible. That's the result that i research ^^

I know that's not may the main goal of that Gdx Texture Packer, but that's the only one i've found which is the nearest to what i want, and being open source.
A Godot importer should be the easier, but i've only found json import, not for atlas extension.

**Comment by metaphore** [comment]
I've added ordering logic into "Grid layout" algorithm, so now it should works more predictable.
Please let me know if that helps.
