### ISSUE TITLE
FlattenPaths option missing

### ISSUE THREAD

**Issue by RUSshy** [crashinvaders/gdx-texture-packer-gui#24]
Hello

With libgdx packer i usually can select to flattenPaths but i can't find that option in the GUI

flattenPaths means it won't care about folder structure and only add file names, i need that

thanks!

**Comment by metaphore** [comment]
Yep, it has been moved under input directory properties dialog. At first you have to check `recursive` and then it will appear.

![image](https://user-images.githubusercontent.com/6159734/28612129-6f114f8a-7218-11e7-85f0-51ef7560a589.png)

**Comment by RUSshy** [comment]
ohhh ok! so it works per directory now?

**Comment by metaphore** [comment]
Since region list is formed from images and directories now, this should be the proper place to configure such behavior.
