### ISSUE TITLE
Chinese language display issue

### ISSUE THREAD

**Issue by Tokenyet** [crashinvaders/gdx-texture-packer-gui#25]
Hi, I'm really like this application! I also want to contribute a Chinese(Traditional) language for this, but application seems not using freetype, so It should be very hard to add Chinese as I thought. 

I made a Chinese option in application, but show nothing because there is no default supported to Chinese characters, so If gdx-texture-packer-gui would add [gdx-freetype](https://github.com/libgdx/libgdx/wiki/Gdx-freetype) in the future,  I would back to help for add 
some .ttf or .fnt to help it work :)

[Chinese Tried Project](https://github.com/Tokenyet/gdx-texture-packer-gui/tree/develop)

**Comment by metaphore** [comment]
Support of Chinese would be great, thanks!
I will look through gdx-freetype integration and will get back to this issue.

**Comment by metaphore** [comment]
@Tokenyet sorry that it took so long, all application fonts are powered by FreeType now. It was a little bit more complicated than I though it would be, so support for CJK fonts activates from downloadable module. I would appreciate if you could find a moment to check current version and revisit Chinese properties file once again right before release, there are number of new strings and should be a few more once I'm done with the rest of the planned features for this update. I will let you know when this file will be ready for revision.

BTW, check out current main screen, maybe there is something obviously wrong with the text render
![chinese](https://user-images.githubusercontent.com/6159734/32400882-b5bdcc1e-c138-11e7-9fec-2e2049c2330e.png)
