### ISSUE TITLE
JSON EXPORT

### ISSUE THREAD

**Issue by damodaranr** [crashinvaders/gdx-texture-packer-gui#26]
Is it possible to generate a JSON Hash export like Texture Packer commercial product. This will be useful in game engines like Phaser.

**Comment by metaphore** [comment]
Project now uses original LibGDX `TexturePacker` class code to pack and export and it's not customizable. However, there were few requests for different export format support, so I'm going to look into it. But, certainly, this will take time and I can't say that such feature will be available soon.

**Comment by FlorentMasson** [comment]
My node.js script to convert from atlas to json (pixi.js compatible) may comes in handy
[convertspritesheet.zip](https://github.com/crashinvaders/gdx-texture-packer-gui/files/2103453/convertspritesheet.zip)

**Comment by metaphore** [comment]
It's been a few years and I'm afraid I still don't have these other export options on the horizon. It's simply too far from the main purpose of the app and there are many other more prioritized LibGDX related features that app is missing. So I'm very sorry to keep you hanging for that long time, but for now, I'm gonna close this issue.

Maybe if there's anyone willing to write this converter from LibGDX texture atlas data file to other formats, I'm happy to assist on integration. But I definitely can't spend time to do it myself now.
