### ISSUE TITLE
Bleeding isn't saved to the project configuration

### ISSUE THREAD

**Issue by WickedShell** [crashinvaders/gdx-texture-packer-gui#3]
When saving a project configuration the bleeding value doesn't appear to be saved or loaded from the configuration. This keeps tripping me up as one of my atlases needs it turned off, while the other needs it on. The net effect is I usually forget to turn it of on one when opening the project and have to rebake the texture after I load in the result and realize the mistake.

Encountered on 4.2.0

**Comment by metaphore** [comment]
Thanks for report!
Yeah, you're right, `bleed` flag is missing in save file. Will include this fix to the next update. Hope this will happen by the end of the week.

**Comment by vito-Z80** [comment]
Дружище, где документация ? ))
Снизу-слева можно кучу галок поставить, но как в них разобраться, не зная английского?
...и как работать с: 
  size: 0, 0
  orig: 0, 0
  offset: 0, 0
нужны все данные, как они формируются и формируются ли вообще ?

P.S.
Прога понравилась. Но либо не могу разобраться с некоторыми моментами, либо не все готово.

**Comment by metaphore** [comment]
@vito-Z80 документация конечно вещь полезная, но боюсь сейчас у меня просто нет времени заняться написанием полноценных гайдов. Но думаю любой человек, который имеет представление о том чт,о такое атласы текстур и работавший с ними в LibGDX, сможет хотябы собрать простейший со стандартным пресетом, а дальше разберётся эксперементируя с разными настройками. По части "для чего нужны конкретные параметры", думаю весьма хорошим подспорьем тут будут всплывающие подсказки #4. Ну и в целом приложение полностью готово к локализации и возможно будет лучше вместо написания гайда потратить время на перевод всех строк на русский.
