### ISSUE TITLE
Atlas Preview Capture Scroll Focus

### ISSUE THREAD

**Issue by raeleus** [crashinvaders/gdx-texture-packer-gui#31]
The Atlas Preview should automatically request scroll focus upon program start or at least whenever the user mouses over the area. I was sitting there for a minute wondering why the zoom wasn't working. It's not obvious that you have to click in the preview area first. Most programs don't operate like that. Thanks for your consideration.

**Comment by metaphore** [comment]
Yep, this is a [one very old thing](https://trello.com/c/qYL8ifT6/32-catch-scroll-events-and-focus-actual-underlying-widget) I can't get over with. Will include it in the next update for sure.

**Comment by raeleus** [comment]
Thanks for the super fast response!
