### ISSUE TITLE
Infinity loop  when packing larger images

### ISSUE THREAD

**Issue by nikolamk** [crashinvaders/gdx-texture-packer-gui#33]
I have 4 images with size of 1080x1920 
When I try to pack this image "Pack processing" last forever. I try with blank white images with the same size and again same infinity pack processing message. 
I have 4.6.0 version 
Here is my window
![untitled](https://user-images.githubusercontent.com/1798279/34063823-f3b7fee0-e1f4-11e7-84ea-d7fa785dfe8e.png)

**Comment by metaphore** [comment]
Thanks for the report. I'm aware of some issues related to packing of big atlases and think this is a good moment to finally look into. Will back to you when I check it.

**Comment by metaphore** [comment]
I no longer can't reproduce this one, seems like _reasonably_ big images get correctly packed, If anyone will run into anything similar, feel free to reopen this one.

**Comment by BambooBandit** [comment]
This is happening to me as well. I'm packing 945 images. Last successful pack, it generated an atlas the size 4096 x 8192. I made some tiny changes to some of the images, and I'm stuck at this now. The changes might have made some of the images slightly larger; I am cutting out whitespace so maybe it's just too large now?
