### ISSUE TITLE
Shortcut keys do not function while keyboard focus is in text field.

### ISSUE THREAD

**Issue by raeleus** [crashinvaders/gdx-texture-packer-gui#35]
Hello. I finally figured out why I've been losing progress besides the other issue I posted. Keyboard shortcuts like Ctrl+S and Ctrl+O do not function when the keyboard focus is set to a text field.

Reproduction steps:
Click inside the file name text field under "Pack general".
Press Ctrl+O

The open dialog does not appear like usual. Thanks for considering this issue and making the best texture packer in the community!

**Comment by metaphore** [comment]
Yep, that's the problem. I will look into it. Thanks for the report.

**Comment by raeleus** [comment]
Thanks for fixing this!

**Comment by metaphore** [comment]
Sure, you're welcome! Please report if anything else is working wrong or can be improved.
