### ISSUE TITLE
Settings Tooltips

### ISSUE THREAD

**Issue by raeleus** [crashinvaders/gdx-texture-packer-gui#4]
Excellent software. Thank you for making this. Can you include text tooltips that describe each option as the user mouses over them? The descriptions can simply be taken from the wiki [here](https://github.com/libgdx/libgdx/wiki/Texture-packer#settings). It would be very helpful for folks that don't know this stuff off the top of their heads. Thanks.

**Comment by metaphore** [comment]
Hey @raeleus, thanks for pointing me out! That's a very idea, will add those tooltips soon.
