### ISSUE TITLE
Ошибка при записи config-файла в каталог с исходными изображениями

### ISSUE THREAD

**Issue by aliexx** [crashinvaders/gdx-texture-packer-gui#5]
Я храню неупакованные изображения в каталоге raw_images, config-файл texturepacker'а для удобства обычно сохраняю там же. В файл записывается такая строка и он загружается  неправильно:
`input=`

Хотелось бы, чтобы в таком случае в config-файл записывалось это:
`input=.`
а то приходится править вручную

**Comment by metaphore** [comment]
Спасибо за информацию! Патч будет включён в очередной минорный релиз
