### ISSUE TITLE
Unspported files alert

### ISSUE THREAD

**Issue by PROSKEY** [crashinvaders/gdx-texture-packer-gui#54]
I was trying to import one file in to texture packer by dragging. and it was not importing it in list and was not displaying any alert. so after checking twice i got the problem, the file was SVG. 

please add alert for unsupported file types if possible.

**Comment by metaphore** [comment]
When you drag'n'droping files into the app, there is an overlay that explicitly states which kind of files is acceptable.

![image](https://user-images.githubusercontent.com/6159734/43702835-ab9f3c14-9963-11e8-9e71-b1b1a98f1e39.png)
