### ISSUE TITLE
[Report] not runn

### ISSUE THREAD

**Issue by kasakage12** [crashinvaders/gdx-texture-packer-gui#59]
not run win10

<details><summary>Application log</summary>

```

```

</details>

**Comment by metaphore** [comment]
Could you please describe the problem in a bit more details. Also would be very helpful if you attach application log, you can see it if you run the program using command line and copypaste the output:

For default installation location issue command in CMD:
```console
java -jar "C:\Program Files (x86)\GdxTexturePacker\gdx-texturepacker.jar"
```

**Comment by metaphore** [comment]
I'm closing this as there is no any additional feedback to reproduce the issue. Feel free to reopen and provide some more info.
