### ISSUE TITLE
Include/Exclude whole atlas from packing

### ISSUE THREAD

**Issue by Hangman** [crashinvaders/gdx-texture-packer-gui#67]
Feature Request:
It would be nice to have the option to exclude an atlas from packing when hitting the "Pack All" button. This could work like a layer in Photoshop that is not visible. 
Three brainstorm ideas how to realize it:
1. Having a little checkbox next to the pack name in the pack list.
2. Context menu entry "include/exclude" toggle. Pack is grayed out in the list when disabled.
3. Button "Pack selected packs" and the possibility to select more than one item from the list.

**Comment by metaphore** [comment]
Thanks for the input. That's actually something I've wanted to implement for quite a while. I'd prefer to have multi-selection for the atlas list, as this way there is an opportunity to edit properties for multiple atlases at once (but this part is for later, now just multi-selection for packing). I'll try to bring this in the next release.

**Comment by Hangman** [comment]
Much appreciated, this will help a lot. Thank you Sir.

**Comment by metaphore** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Let user select what atlases to pack with "pack-multiple" button](https://trello.com/c/ifOg4c7R/216-let-user-select-what-atlases-to-pack-with-pack-multiple-button)

**Comment by metaphore** [comment]
"Better later than never" :smiling_face_with_tear: 

https://user-images.githubusercontent.com/6159734/211654357-c8b5e4a0-3211-41f4-adab-3efd1a399a75.mp4

**Comment by Hangman** [comment]
Nice, thanks!
