### ISSUE TITLE
Make it possible to sort files manually

### ISSUE THREAD

**Issue by bvn13** [crashinvaders/gdx-texture-packer-gui#68]
It needs:

1) to sort manually (by drag-n-drop or by buttons in panel)
2) to select multiple files (etc. to delete them)

**Comment by metaphore** [comment]
You can select multiple files by pressing Ctrl/Shift.
Why do you need to sort them manually?

**Comment by bvn13** [comment]
@metaphore 
I am not able to select multiple files neither with Ctrl nor with Shift (last release from .zip)
Sort manually... I've thought it helps me to rearrange them in atlas but now I understand it might be unneccessary. How do I obtain textures from an atlas? by name?

**Comment by metaphore** [comment]
Read about what texture atlases are and how to work with them https://github.com/libgdx/libgdx/wiki/Texture-packer#textureatlas
