### ISSUE TITLE
Changing language sometimes causes NullPointerException

### ISSUE THREAD

**Issue by terafog** [crashinvaders/gdx-texture-packer-gui#7]
Changing the language via the menu (Tools > change language) sometimes crashes the application with a NullPointerException.
E.g. after changing EN->RU:
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.kotcrab.vis.ui.widget.Tooltip$DisplayTask.run(Tooltip.java:251)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:257)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:208)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```
The cause seems to be that the application tries to display a tooltip while the language is changing.
Because of that, the crash seems to only be happening when clicking specific areas of the new language menu entry.
Clicking on areas with gui elements with tooltips underneath produces a crash while other areas are fine. 

Example of the crash area (in yellow) and the area that is fine to click (in green):
![Crash Area](http://i.imgur.com/nHU2pwG.png)

**Comment by metaphore** [comment]
Thanks for the report.
Yes, this is known bug. [It's related to VisUI](https://github.com/kotcrab/vis-editor/issues/241) and has been fixed already, but we still have to wait until new VisUI version will be published to use it.

I will keep this issue open until the moment we update VisUI.

**Comment by metaphore** [comment]
I made a temporal patch. Probably this will be fine for now

**Comment by metaphore** [comment]
Looks like we finally overcome this one. Please let me know if it will happen in one of a recent versions.
