### ISSUE TITLE
Windows defender blocking install

### ISSUE THREAD

**Issue by FlorentMasson** [crashinvaders/gdx-texture-packer-gui#70]
With gdx-texturepacker-4.8.2.exe

![image](https://user-images.githubusercontent.com/9975455/62692848-adff3d80-b9d1-11e9-9e3d-2205769e48ea.png)

**Comment by metaphore** [comment]
Hi, thanks for the input.
To bypass this warning hit "More info" and proceed with accepting the app to run.

This message displays for the applications that are not signed with a valid certificate. Although it's not a big deal for the app, but definitely a little pain for users. I will check on the options to make the installer recognized as "safe" for Windows defense system.

**Comment by metaphore** [comment]
Just to give everyone an update, after a few brief attempts to set up the signing process for the app, I didn't succeed with a quick solution, my brain got melted a bit and for now, I have to capitulate on that. 

If someone is experienced and actually knows the entire signing process for the Windows apps and can provide help for establishing it, please reach me out and I would be happy to proceed. Until then, I'm gonna close this and put this whole task on the shelf.
