### ISSUE TITLE
[Report] Can't Save the TexturePack

### ISSUE THREAD

**Issue by NastyKid** [crashinvaders/gdx-texture-packer-gui#72]
When i try to save the Texture. it will crash

<details><summary>Application log</summary>

```

```

</details>

**Comment by metaphore** [comment]
I would appreciate if you could run the program from the console and copypaste the output, there should be something on crash I believe. 

For Windows: `cd` to an installation folder (usually `C:\Program Files (x86)\GdxTexturePacker` and run from CMD `java -jar gdx-texturepacker.jar`.

Thanks in advance!

**Comment by metaphore** [comment]
Closed due to inactivity. Feel free to reopen if you have a log.
