### ISSUE TITLE
ImageFactory feature?

### ISSUE THREAD

**Issue by payne911** [crashinvaders/gdx-texture-packer-gui#73]
How easy would it be to integrate an option to generate some kind of `ImageFactory` class along with the atlas?
The output would look something like [this](https://github.com/payne911/Arise_Deeper/blob/master/core/src/com/payne/games/assets/ImageFactory.java).
It could probably pre-pend the folder path leading to each individual image as well, for a more "structured" naming convention of the generated file (as an extra option, of course).
Seems like an "easy enough" feature to integrate. I could try to help out, but don't really know where to start.

There are two main concerns that led me to writing this issue:
1) The suggested way of using a `TextureAtlas` is to cache the results of the queries. This means that despite not being necessary, it is indeed something possibly most people would want to integrate in their projects.
2) In order to get anything from a `TextureAtlas`, you must know the name of the specific image you want. Using a String directly in the code becomes a problem in terms of maintainability as soon as you need to query the Atlas twice for the same thing, in different classes.

I believe despite there being very many different approaches to solving this kind of problem, I think proposing at least one quick-way of doing so in an integrated way would not hurt anyone. I also believe that the Factory design pattern fits quite well in this scenario.

**Comment by metaphore** [comment]
Sorry to turn it down that quickly, but I described the reason for this in the Discord conversation.

A little brief: the case is very specific and generally outside of the scope of the library. Gradle/IDE plugin that will generate such classes feels more like a proper solution.

But thanks for the idea anyway.

**Comment by payne911** [comment]
All good.

For anyone interested, someone wrote [this `AtlasEnumGenerator`](https://github.com/tommyettinger/DawnLikeAtlas/blob/fdce763844ff2016c1d745a5a1314d6ef3f9228c/src/test/java/AtlasEnumGenerator.java) to generate [such a file](https://github.com/tommyettinger/DawnLikeAtlas/blob/fdce763844ff2016c1d745a5a1314d6ef3f9228c/atlas/Dawnlike.java).
