### ISSUE TITLE
Can not change pack files order !

### ISSUE THREAD

**Issue by vohuu** [crashinvaders/gdx-texture-packer-gui#87]
I selected files by these other: "Smoke (1).png" "Smoke (2).png" "Smoke (10).png".
![image](https://user-images.githubusercontent.com/11476004/91963787-8a273c00-ed38-11ea-8d92-75e71484696a.png)
But order on "Pack files" is not correctly.
![image](https://user-images.githubusercontent.com/11476004/91963845-a1fec000-ed38-11ea-825b-8f2d92f6ede8.png)
"Smoke (1).png" "Smoke (10).png" "Smoke (2).png" is not the same when im imported !

Then I use "Grid layout" option, program will not working correctly ! And have no way to change index imported sprites.

**Comment by metaphore** [comment]
Yep, they are ordered strictly by the name (string comparison) which appears to be correct on the screenshot.

The original LibGDX packaging algorithm doesn't guarantee any order, but if "Grid layout" is used, I believe it should follow the [indices](https://github.com/libgdx/libgdx/wiki/Texture-packer#image-indexes). To define an index for an image, it should have a suffix like `_N`.
For example, in your case, the images should be called _Smoke_1.png_, _Smoke_2.png_ etc

**Comment by metaphore** [comment]
I guess this one can be considered as solved. Happy to reopen and continue the discussion if needed.
