### ISSUE TITLE
can not pack in version 4.9.0 on mac OS

### ISSUE THREAD

**Issue by thawri1** [crashinvaders/gdx-texture-packer-gui#89]
after click pack or pack All button app freeze .
operation system:mac os v10.15.6
texture packer 4.8.2 is working.

**Comment by metaphore** [comment]
Hi @thawri1 thanks for the report.

That sounds like a new bug. Could you please tell what is the output texture format and compression selected for the pack that freezes the app? By chance did you try it with any other texture packer projects?

There is a good chance that the logs might contain something useful to locate the source. I'd appreciate it if you could make the app freeze and then share the latest log file from `/home/<username>/.gdxtexturepackergui/logs/`.

**Comment by thawri1** [comment]
after uninstall 4.8.2 and reinstall 4.9.0 it working without issue.
maybe problem was my java.
after installing 4.9 for first time I can not open it until reinstalling java.
Sorry I took your time.

**Comment by metaphore** [comment]
No worries, it's still something abnormal in the program functioning and better to be tracked to the actual cause. Please if there will be any other similar issue feel free to reopen this issue and provide as much as possible information.
